### ISSUE TITLE
Expose Speedy.js Version 

### ISSUE THREAD

**Issue by MaxGraey** [MichaReiser/speedy.js-saas#2]
It seems need some work on speedy.js compiler side as well

**Comment by MichaReiser** [comment]
Probably I could include both version numbers? I prefer to also have the version of the service somewhere.

Maybe a JSON response?

```
/version
{ 
  compiler: "0.0.14",
  typescript: "...",
  service: "1.0.0"
}
```

I think I can implement it without any changes to the Compiler. Simply requiring the package.jsons of the packages should be sufficient.

**Comment by MaxGraey** [comment]
Up to you)

**Comment by MaxGraey** [comment]
But if the update of the compiler follows the same way update of the service, then we can use one uniform version for both. What do you think?

**Comment by MichaReiser** [comment]
That's true. But it might be that I need to update the service without that I want to update the compiler. So I think I prefer exposing multiple versions.

**Comment by MaxGraey** [comment]
ok, I don't mind

**Comment by MichaReiser** [comment]
The newest version is deployed. The output is:

```json
{"speedyjs-compiler":"0.0.14","typescript":"2.3.3","speedyjs-saas":"0.0.15"}
```
