### ISSUE TITLE
saveWast not works

### ISSUE THREAD

**Issue by MaxGraey** [MichaReiser/speedy.js-saas#4]
![not-wast](https://user-images.githubusercontent.com/1301959/27132682-6b7b6ef8-5118-11e7-9ba1-d97ddcddce54.png)

**Comment by MichaReiser** [comment]
Will take some time until all builds have completed. Sorry, for this issue.

**Comment by MichaReiser** [comment]
... Not yet deployed

**Comment by MaxGraey** [comment]
Still deploying? I got 0.0.15 version

**Comment by MichaReiser** [comment]
Deployed
